name: Check linux-fw-cutter.py and WHENCE.yaml

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y rdfind
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    - name: Test WHENCE.yaml
      run: |
        firmware_version=$(./linux-fw-cutter.py info -n 1 | grep firmware_version | cut -d ' ' -f 2)
        pushd ..
        git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
        cd linux-firmware
        git checkout "${firmware_version}"
        popd
        ./linux-fw-cutter.py check -s ../linux-firmware
    - name: Compare linux-firmware and linux-fw-cutter compressed install output
      run: |
        pushd ../linux-firmware
        mkdir ../firmware-linux-xz
        ./copy-firmware.sh --xz ../firmware-linux-xz
        popd
        ./linux-fw-cutter.py install -s ../linux-firmware -d ../linux-fw-cutter-xz -C xz
        diff -qr ../firmware-linux-xz ../linux-fw-cutter-xz